### PR TITLE
[Feature]: add Input(default)

### PR DESCRIPTION
**Pull request by SEOKKAMONI**
## Overview

add input in @toss/ui
- default input

### CODE REVIEW

**Comment by dmswl98** [comment]
Hello, I thought it would be convenient for you if I respond here, so I'm leaving my opinion here.

Looking at the chromatic-deploy actions log, it seems like the `storybook build` is not executing properly. 
Please check if the storybook builds well locally and let me know again. 
To add a comment, it might be good to change from `npx` to `pnpm dlx` in the chromatic_publish.sh script command.

**Comment by SEOKKAMONI** [comment]
@dmswl98 

image

build is successfully but node-modules is not installed when installing pnpm I think there is a problem here

**Comment by dmswl98** [comment]
@SEOKKAMONI 
If there is a package that depends on @toss/ui, you should first build that package and then execute the `Publish Chromatic` step.
: you can resolve this by creating a step to build that package before the `Publish Chromatic` step.

[Related Link](https://velog.io/@dmswl98/design-system-%ED%8C%A8%ED%82%A4%EC%A7%80%EC%97%90-%ED%8A%B9%EC%A0%95-%ED%8C%A8%ED%82%A4%EC%A7%80%EB%A5%BC-%EC%9D%98%EC%A1%B4%EC%84%B1%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0with-turborepo-storybook-chromatic-github-actions-tailwind)
[[@dmswl98/turborepo-chromatic] chromatic-deploy actions log](https://github.com/dmswl98/turborepo-chromatic/actions/runs/6369030093/job/17288887201)

**Comment by SEOKKAMONI** [comment]
> @SEOKKAMONI If there is a package that depends on @toss/ui, you should first build that package and then execute the `Publish Chromatic` step. : you can resolve this by creating a step to build that package before the `Publish Chromatic` step.
> 
> And is the chromatic script running well in your local environment?
> 
> [Related Link](https://velog.io/@dmswl98/design-system-%ED%8C%A8%ED%82%A4%EC%A7%80%EC%97%90-%ED%8A%B9%EC%A0%95-%ED%8C%A8%ED%82%A4%EC%A7%80%EB%A5%BC-%EC%9D%98%EC%A1%B4%EC%84%B1%EC%9C%BC%EB%A1%9C-%EC%B6%94%EA%B0%80%ED%95%98%EA%B8%B0with-turborepo-storybook-chromatic-github-actions-tailwind) [[@dmswl98/turborepo-chromatic] chromatic-deploy actions log](https://github.com/dmswl98/turborepo-chromatic/actions/runs/6369030093/job/17288887201)

Thank you for @dmswl98 !!

여기부터는 한국어로 하겠습니당.. ㅎㅎ

너무 감사드립니다 ㅠㅠ 정말 블로그 글 써주신 것도 이렇게 도와주러 오신 것도.. 너무 감사드려요
build 시 pnpm install을 할 때 node-modules가 ui package에 깔리지 않아 생기는 문제였고
이 문제는 packages > @toss > ui 3단계로 가는 구조 때문이었던 것 같습니다
packages > ui로 바로 가는 구조로 바꾸니 해결되었습니다!! 정말 감사합니다

**Pull request merged**
